#include <BleCombo.h>
#include "Print.h"

#define KEY_LEFT_CTRL 0x80;
#define KEY_LEFT_SHIFT 0x81;
#define KEY_LEFT_ALT 0x82;
#define KEY_LEFT_GUI 0x83;
#define KEY_RIGHT_CTRL 0x84;
#define KEY_RIGHT_SHIFT 0x85;
#define KEY_RIGHT_ALT 0x86;
#define KEY_RIGHT_GUI 0x87;
//0x88 - 0x8B none
#define KEY_A 0x8C;
#define KEY_B 0x8D;
#define KEY_C 0x8E;
#define KEY_D 0x8F;
#define KEY_E 0x90;
#define KEY_F 0x91;
#define KEY_G 0x92;
#define KEY_H 0x93;
#define KEY_I 0x94;
#define KEY_J 0x95;
#define KEY_K 0x96;
#define KEY_L 0x97;
#define KEY_M 0x98;
#define KEY_N 0x99;
#define KEY_O 0x9A;
#define KEY_P 0x9B;
#define KEY_Q 0x9C;
#define KEY_R 0x9D;
#define KEY_S 0x9E;
#define KEY_T 0x9F;
#define KEY_U 0xA0;
#define KEY_V 0xA1;
#define KEY_W 0xA2;
#define KEY_X 0xA3;
#define KEY_Y 0xA4;
#define KEY_Z 0xA5;

#define KEY_1 0xA6;
#define KEY_2 0xA7;
#define KEY_3 0xA8;
#define KEY_4 0xA9;
#define KEY_5 0xAA;
#define KEY_6 0xAB;
#define KEY_7 0xAC;
#define KEY_8 0xAD;
#define KEY_9 0xAE;
#define KEY_0 0xAF;
#define KEY_RETURN 0xB0;
#define KEY_ESC 0xB1;
#define KEY_BACKSPACE 0xB2;
#define KEY_TAB 0xB3;
#define KEY_SPACE 0xB4;
#define KEY_MINUS 0xB5;
#define KEY_EQUAL 0xB6;
#define KEY_BRACKET_LEFT 0xB7;
#define KEY_BRACKET_RIGHT 0xB8;
#define KEY_BACKSLASH 0xB9;
#define KEY_SEMICOLON 0xBB;
#define KEY_QUOTE 0xBC;
#define KEY_TILDE 0xBD;
#define KEY_COMMA 0xBE;
#define KEY_PERIOD 0xBF;
#define KEY_SLASH 0xC0; 
#define KEY_CAPS_LOCK 0xC1;
#define KEY_F1 0xC2;
#define KEY_F2 0xC3;
#define KEY_F3 0xC4;
#define KEY_F4 0xC5;
#define KEY_F5 0xC6;
#define KEY_F6 0xC7;
#define KEY_F7 0xC8;
#define KEY_F8 0xC9;
#define KEY_F9 0xCA;
#define KEY_F10 0xCB;
#define KEY_F11 0xCC;
#define KEY_F12 0xCD;
#define KEY_PRINTSCREEN 0xCE;
#define KEY_SCROLL_LOCK 0xCF;
#define KEY_PAUSE 0xD0;
#define KEY_INSERT 0xD1;
#define KEY_HOME 0xD2;
#define KEY_PAGE_UP 0xD3;
#define KEY_DELETE 0xD4;
#define KEY_END 0xD5;
#define KEY_PAGE_DOWN 0xD6;
#define KEY_RIGHT_ARROW 0xD7;
#define KEY_LEFT_ARROW 0xD8;
#define KEY_DOWN_ARROW 0xD9;
#define KEY_UP_ARROW 0xDA;
#define KEY_NUM_LOCK 0xDB;
#define KEYPAD_DIVIDE 0xDC;
#define KEYPAD_MULTIPLY 0xDD;
#define KEYPAD_SUBTRACT 0xDE;
#define KEYPAD_ADD 0xDF;
#define KEYPAD_ENTER 0xE0;
#define KEYPAD_1 0xE1;
#define KEYPAD_2 0xE2;
#define KEYPAD_3 0xE3;
#define KEYPAD_4 0xE4;
#define KEYPAD_5 0xE5;
#define KEYPAD_6 0xE6;
#define KEYPAD_7 0xE7;
#define KEYPAD_8 0xE8;
#define KEYPAD_9 0xE9;
#define KEYPAD_0 0xEA;
#define KEYPAD_DOT 0xEB;
#define KEY_APPLICATION 0xED;
#define KEY_F13 0xF0;
#define KEY_F14 0xF1;
#define KEY_F15 0xF2;
#define KEY_F16 0xF3;
#define KEY_F17 0xF4;
#define KEY_F18 0xF5;
#define KEY_F19 0xF6;
#define KEY_F20 0xF7;
#define KEY_F21 0xF8;
#define KEY_F22 0xF9;
#define KEY_F23 0xFA;
#define KEY_F24 0xFB;

class Keyboard_ : public Print
{
public:
    void begin();
    void end(void);
    size_t write(uint8_t k);
    size_t write(const MediaKeyReport m);
    size_t write(const uint8_t *buffer, size_t size);
    size_t press(uint8_t k);
    size_t press(const MediaKeyReport m);
    size_t release(uint8_t k);
    size_t release(const MediaKeyReport k);
    void releaseAll(void);
};

extern Keyboard_ Keyboard;